<?php

namespace ML\billetterieBundle\Repository;
use Symfony\Component\Validator\Constraints\Count;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkBillets($dateVisite) {
        $qb = $this->createQueryBuilder('c')
        ->select('sum(c.nbrBillets)')
        ->where('c.dateVisite = :dateVisite')
        ->setParameter(':dateVisite', $dateVisite)
        ->getQuery()
        ->getSingleScalarResult();

        return $qb >= 1000 ? true : false;
    }
}